import type { Metadata } from "next";
import { DM_Sans, Squada_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/section/Navbar/Navbar";




const squada = Squada_One({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-squada-one'
})

const fontDm = DM_Sans({
  weight: ["400", "500", "600", "700", "800", "900", "1000"],
  subsets: ['latin'],
  variable: "--font-dm"
})



export const metadata: Metadata = {
  title: "Sport News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontDm.variable} ${squada.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
