import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/section/Navbar/Navbar";



const fontDm = DM_Sans({
  weight: ["400" , "500" , "600" ,"700" ,"800" ,"900" ,"1000"],
  subsets: ['latin'],
  variable: "--font-dm"
})



export const metadata: Metadata = {
  title: "Sport News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontDm.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
